name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Villa is affected?
      options:
        - Authentication (passkeys, login)
        - Profile (nickname, avatar)
        - SDK (@villa/sdk)
        - Developer Portal (developers.villa.cash)
        - Smart Contracts
        - CI/CD / Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: When I click the login button, nothing happens...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this happen?
      options:
        - Production (villa.cash)
        - Staging (beta.villa.cash)
        - Preview (dev-1/dev-2.villa.cash)
        - Local development
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs / Error Messages
      description: Any relevant error messages from browser console or terminal
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
