name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you need.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Villa would this affect?
      options:
        - Authentication (passkeys, login)
        - Profile (nickname, avatar)
        - SDK (@villa/sdk)
        - Developer Portal (developers.villa.cash)
        - Smart Contracts
        - CI/CD / Infrastructure
        - New Area
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? Who benefits?
      placeholder: |
        As a [user type], I want to [do something] so that [benefit].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How important is this feature?
      options:
        - Nice to have
        - Would significantly improve experience
        - Blocking a use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to work on this?
      options:
        - label: I'd like to implement this feature myself
        - label: I can help test this feature
        - label: I can help with documentation
